name: amigo_secreto
description: A secret santa flutter project.

publish_to: "none"

version: 0.0.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  fonts:
    - family: Courier-Prime
      fonts:
        - asset: assets/fonts/courier-prime/courier-prime.regular.ttf
        - asset: assets/fonts/courier-prime/courier-prime.italic.ttf
          style: italic
        - asset: assets/fonts/courier-prime/courier-prime.bold.ttf
          weight: 700
        - asset: assets/fonts/courier-prime/courier-prime.bold-italic.ttf
          weight: 700
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700
